---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19.2

inputs:
  - name: dp-otel-go
    path: dp-otel-go

run:
  path: dp-otel-go/ci/scripts/build.sh
